describe("Cypress_test", () => {
  it("tests Cypress_test", () => {
    cy.viewport(1127, 947);
    cy.visit("https://zucksharof.onrender.com/users/signin");
    cy.get("div.container a").click();
    cy.get("#firstNameTextField").click();
    cy.get("#firstNameTextField").type("Zuhriddin");
    cy.get("#lastNameTextField").click();
    cy.get("#lastNameTextField").type("Sharofiddinov");
    cy.get("#emailTextField").click();
    cy.get("#emailTextField").type("zukhriddinsh@gmail.com");
    cy.get("#passwordTextField").click();
    cy.get("#passwordTextField").type("1234567");
    cy.get("#confirmPasswordTextField").click();
    cy.get("#confirmPasswordTextField").type("1234567");
    cy.get("#emailTextField").dblclick();
    cy.get("#emailTextField").click();
    cy.get("#emailTextField").dblclick();
    cy.get("#emailTextField").type("zukhriddinsh@hotmail.com");
    cy.get("button").click();
    cy.get("label:nth-of-type(1) > input").click();
    cy.get("button").click();
    cy.get("button path").click();
    cy.get("button").click();
    cy.get("a:nth-of-type(7)").click();
    cy.get("form").click();
    cy.get("#emailTextField").click();
    cy.get("#emailTextField").type("zukhriddinsh@gmail.com");
    cy.get("#emailTextField").dblclick();
    cy.get("#emailTextField").click();
    cy.get("#emailTextField").dblclick();
    cy.get("#emailTextField").type("zukhriddinsh@hotmail.com");
    cy.get("#passowordTextField").click();
    cy.get("#passowordTextField").type("1234567");
    cy.get("button.btn-primary").click();
    cy.get("a:nth-of-type(3)").click();
    cy.get("div > div:nth-of-type(2) > a").click();
    cy.get("#itemTextField").click();
    cy.get("#itemTextField").type("N");
    cy.get("#itemTextField").type("New project");
    cy.get("#QtyTextField").click();
    cy.get("#QtyTextField").type("1");
    cy.get("#goalTextField").click();
    cy.get("#goalTextField").type("Data related jobs");
    cy.get("#statusTextField").click();
    cy.get("#statusTextField").type("Active");
    cy.get("#messageTextArea").click();
    cy.get("#messageTextArea").type("New project");
    cy.get("button.btn-primary").click();
    cy.get("tr:nth-of-type(2) > td:nth-of-type(5) svg").click();
    cy.get("#itemTextField").click();
    cy.get("#itemTextField").dblclick();
    cy.get("#itemTextField").click();
    cy.get("#itemTextField").dblclick();
    cy.get("#itemTextField").click();
    cy.get("#itemTextField").click();
    cy.get("#itemTextField").click();
    cy.get("#itemTextField").type("Da");
    cy.get("#itemTextField").type("Database project");
    cy.get("#messageTextArea").dblclick();
    cy.get("#messageTextArea").click();
    cy.get("#messageTextArea").type("Th");
    cy.get("#messageTextArea").type("This should be done");
    cy.get("button.btn-primary").click();
    cy.get("tr:nth-of-type(2) > td:nth-of-type(6) svg").click();
  });
});
//# recorderSourceMap=BCBDBEBFBGBHBIBJBKBLBMBNBOBPBQBRBSBTBUBVBWBXBYBZBaBbBcBdBeBfBgBBhBBiBBjBBkBBlBBmBBnBAnBBoBBpBBqBBrBBsBBtBBuBBvBBwBBxBByBBzBB0BB1BB2BB3BB4BB5BB6BA6BB7BB8BB9BB+BA+BB/BBgCB
